yes

diff --git a/0x0C-web_server/0-transfer_file b/0x0C-web_server/0-transfer_file
--- a/0x0C-web_server/0-transfer_file
+++ b/0x0C-web_server/0-transfer_file
@@ -1,14 +1,23 @@
-#!/usr/bin/env bash
-# Script that will transfer a file from our client to a server
+#!/bin/bash
 
-if [ "$#" -ne 4 ]; then
-echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
-exit 1
+# Check if the number of parameters is less than 4
+if [ "$#" -lt 4 ]; then
+    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
+    exit 1
 fi
 
-FILE="$1"
-IP="$2"
-USERNAME="$3"
-PATH_TO_SSH_KEY="$4"
+# Assign parameters to variables
+path_to_file="$1"
+ip="$2"
+username="$3"
+path_to_ssh_key="$4"
 
-scp -i "$SSH_KEY" -o StrictHostKeyChecking=no "$FILE" "$USERNAME"@"$SERVER_IP":~/
+# Transfer the file using scp with strict host key checking disabled
+scp -o StrictHostKeyChecking=no -i "$path_to_ssh_key" "$path_to_file" "$username@$ip":~/ 
+
+# Check if scp command was successful
+if [ $? -eq 0 ]; then
+    echo "File successfully transferred to $username@$ip:~/"
+else
+    echo "Error: File transfer failed."
+fi
